baseURL = "https://akutschi.gitlab.io/docs/"
languageCode = "en-us"
title = "docs"
theme = "dokugo"
enableEmoji = true  

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  homeText = "No eye candy!"
  dateFormat = "2006-01-02"

[params.footer]
  footerText = "This page is primarily a private page and contains the documentation for various projects. The blog and the documentation are more or less notepads to write down things and to explain them to myself."
  copyrightyear = "2019-2020"
  copyrightlink = "https://gitlab.com" 
  copyrightname = "akutschi"  
  github = "https://github.com/akutschi/dokugo"
  gitlab = "https://gitlab.com/akutschi/dokugo"

[markup]
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = true
    style = "solarized-dark"
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
   [[menu.main]]
    name = "Documentation"
    url = "/documentation/"
    weight = 4
